services:
  # Base services - no profile assigned, will be started if a dependent service is run.
  housekeeping-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password@
    ports:
      - "54320:5432"
    volumes:
      - housekeeping_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  housekeeping-db-migrations:
    image: liquibase/liquibase:4.32-alpine
    volumes:
      - ./infra/Housekeeping.Database:/app
    depends_on:
      housekeeping-db:
        condition: service_healthy
    working_dir: /app
    entrypoint: /bin/sh
    command:
      - -c
      - |
        echo 'Running database migrations...'
        liquibase update --defaults-file liquibase.setup.properties --url=jdbc:postgresql://housekeeping-db:5432/postgres
        liquibase update --defaults-file liquibase.servicebus.properties --url=jdbc:postgresql://housekeeping-db:5432/service_bus
        liquibase update --url=jdbc:postgresql://housekeeping-db:5432/housekeeping
        echo 'Database migrations completed successfully!'

  # Profiled Services
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.3
    profiles: ["aspire"]
    ports:
      - "18140:18888"
      - "18890:18890"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  housekeeping-api:
    build:
      context: .
      dockerfile: src/Housekeeping.Api/Dockerfile
    ports:
      - "8201:8080"
      - "8202:8081"
    depends_on:
      - postgres
      - housekeeping-database
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__housekeeping: "Host=postgres;Port=5432;Database=housekeeping;Username=postgres;Password=password@"
      ConnectionStrings__service-bus: "Host=postgres;Port=5432;Database=service_bus;Username=postgres;Password=password@"
    profiles:
      - api
      - aspire

  housekeeping-backoffice:
    build:
      context: .
      dockerfile: src/Housekeeping.BackOffice/Dockerfile
    ports:
      - "8203:8080"
    depends_on:
      - postgres
      - housekeeping-database
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__housekeeping: "Host=postgres;Port=5432;Database=housekeeping;Username=postgres;Password=password@"
      ConnectionStrings__service-bus: "Host=postgres;Port=5432;Database=service_bus;Username=postgres;Password=password@"
    profiles:
      - backoffice
      - aspire

  housekeeping-orleans:
    build:
      context: .
      dockerfile: src/Housekeeping.BackOffice.Orleans/Dockerfile
    ports:
      - "8204:8080"
      - "8205:8081"
    depends_on:
      - postgres
      - housekeeping-database
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__housekeeping: "Host=postgres;Port=5432;Database=housekeeping;Username=postgres;Password=password@"
      ConnectionStrings__service-bus: "Host=postgres;Port=5432;Database=service_bus;Username=postgres;Password=password@"
    profiles:
      - backoffice
      - aspire

  housekeeping-aspire:
    build:
      context: .
      dockerfile: src/Housekeeping.AppHost/Dockerfile
    ports:
      - "18200:8080"
      - "18201:8081"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    profiles:
      - aspire

volumes:
  postgres_data:
