# Liquibase properties for service bus database
changeLogFile: Liquibase/service_bus/changelog.xml
url: jdbc:postgresql://host.docker.internal:54320/service_bus
username: postgres
password: password@
liquibase.hub.mode: off