# Liquibase properties for Housekeeping database
changeLogFile: Liquibase/changelog.xml
url: jdbc:postgresql://host.docker.internal:54320/housekeeping
username: postgres
password: password@
liquibase.hub.mode: off