# Liquibase properties for initial database setup
changeLogFile: Liquibase/setup.xml
url: jdbc:postgresql://host.docker.internal:54320/postgres
username: postgres
password: password@
liquibase.hub.mode: off