// Generated by DbCommandSourceGenerator
public partial record CreateUserCommand : Operations.Extensions.Abstractions.Dapper.IDbParamsProvider
{
    public object ToDbParams()
    {
        return new { UserName = UserName, Email = Email };
    }
}

// Generated command handler (if configured)
public class CreateUserCommandHandler : Wolverine.IMessageHandler<CreateUserCommand>
{
    private readonly System.Data.Common.DbDataSource _dataSource;

    public CreateUserCommandHandler(System.Data.Common.DbDataSource dataSource)
    {
        _dataSource = dataSource;
    }

    public async Task<int> Handle(CreateUserCommand command, CancellationToken cancellationToken)
    {
        var dbParams = command.ToDbParams();
        // Using Dapper to execute the stored procedure
        return await Dapper.SqlMapper.ExecuteAsync(
            _dataSource.CreateConnection(),
            "dbo.CreateUser",
            dbParams,
            commandType: System.Data.CommandType.StoredProcedure
        );
    }
}