services:
  accounting:
    image: accounting
    build:
      context: .
      dockerfile: Accounting/Dockerfile

  accounting.backend:
    image: accounting.backend
    build:
      context: .
      dockerfile: Accounting.Backend/Dockerfile

  accounting.api:
    image: accounting.api
    build:
      context: .
      dockerfile: Accounting.Api/Dockerfile

  billing.api:
    image: billing.api
    build:
      context: .
      dockerfile: Billing.Api/Dockerfile

  billing.backend:
    image: billing.backend
    build:
      context: .
      dockerfile: Billing.Backend/Dockerfile
