// Copyright (c) ABCDEG. All rights reserved.

namespace Operations.Extensions.SourceGenerators.Tests.DbCommand;

public abstract class DbCommandSourceGenTestsBase
{
    protected const string GeneratedCodeHeader = """
                                                 // <auto-generated/>
                                                 #nullable enable

                                                 namespace TestNamespace;
                                                 """;

    protected const string SourceImports = """
                                           using Operations.Extensions.Abstractions.Dapper;
                                           using Operations.Extensions.Abstractions.Messaging;

                                           namespace TestNamespace;
                                           """;

    protected static void GeneratedCodeShouldMatchExpected(string generatedCode, string expectedCode)
    {
        NormalizeGeneratedCode(generatedCode).ShouldBe(NormalizeGeneratedCode(expectedCode));
    }

    private static string NormalizeGeneratedCode(string? code)
    {
        if (string.IsNullOrEmpty(code))
            return string.Empty;

        return code
            .Replace("\r\n", "\n")
            .Replace("\r", "\n")
            .Trim()
            .Replace(" ", "")
            .Replace("\t", "")
            .Replace("\n", "");
    }
}
