// Copyright (c) ABCDEG. All rights reserved.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Operations.Extensions.Dapper;
using Operations.Extensions.Messaging;
using Operations.Extensions.SourceGenerators.DbCommand;
using Xunit;

namespace Operations.Extensions.Tests;

public class DbCommandSourceGeneratorTests
{
    [Fact]
    public async Task GeneratesDbOpsForSimpleRecord()
    {
        const string source = """
            using Operations.Extensions.Dapper;
            using Operations.Extensions.Messaging;

            namespace TestNamespace;

            [DbCommand(sp: "test.create_user", nonQuery: true, paramsCase: DbParamsCase.SnakeCase)]
            public partial record CreateUserCommand(string FirstName, string LastName) : ICommand<int>;
            """;

        const string expectedDbOps = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial record CreateUserCommand : global::Operations.Extensions.Dapper.IDbParamsProvider
            {
                public global::System.Object ToDbParams()
                {
                    var p = new {
                        first_name = this.FirstName,
                        last_name = this.LastName
                    };
                    return p;
                }
            }
            """;

        const string expectedHandler = """
            // <auto-generated/>
            #nullable enable

            using System.Threading.Tasks;
            using Dapper;
            using System.Data;

            namespace TestNamespace;

            public static class CreateUserCommandHandler
            {
                public static async Task<int> HandleAsync(global::TestNamespace.CreateUserCommand command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
                {
                    await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                    var dbParams = command.ToDbParams();
                    return await connection.ExecuteAsync(new CommandDefinition("test.create_user", dbParams, commandType: CommandType.StoredProcedure, cancellationToken: cancellationToken));
                }
            }
            """;

        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace_CreateUserCommand.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace_CreateUserCommand.CreateUserCommandHandler.g.cs", expectedHandler)
                },
                ReferenceAssemblies = GetReferenceAssemblies()
            }
        }.RunAsync();
    }

    [Fact]
    public async Task GeneratesQueryHandlerForEnumerableResult()
    {
        const string source = """
            using Operations.Extensions.Dapper;
            using Operations.Extensions.Messaging;
            using System.Collections.Generic;

            namespace TestNamespace;

            public class User { public string Name { get; set; } }

            [DbCommand(sql: "SELECT * FROM users WHERE active = @active", paramsCase: DbParamsCase.SnakeCase)]
            public partial record GetUsersQuery(bool Active) : ICommand<IEnumerable<User>>;
            """;

        const string expectedHandler = """
            // <auto-generated/>
            #nullable enable

            using System.Threading.Tasks;
            using Dapper;
            using System.Data;

            namespace TestNamespace;

            public static class GetUsersQueryHandler
            {
                public static async Task<global::System.Collections.Generic.IEnumerable<global::TestNamespace.User>> HandleAsync(global::TestNamespace.GetUsersQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
                {
                    await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                    var dbParams = command.ToDbParams();
                    return await connection.QueryAsync<global::TestNamespace.User>(new CommandDefinition("SELECT * FROM users WHERE active = @active", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
                }
            }
            """;

        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace_GetUsersQuery.DbOps.g.cs", SourceText.From(GetExpectedDbOpsForGetUsersQuery(), System.Text.Encoding.UTF8)),
                    (typeof(DbCommandSourceGenerator), "TestNamespace_GetUsersQuery.GetUsersQueryHandler.g.cs", expectedHandler)
                },
                ReferenceAssemblies = GetReferenceAssemblies()
            }
        }.RunAsync();
    }

    [Fact]
    public async Task GeneratesScalarQueryHandler()
    {
        const string source = """
            using Operations.Extensions.Dapper;
            using Operations.Extensions.Messaging;

            namespace TestNamespace;

            [DbCommand(sql: "SELECT COUNT(*) FROM users", paramsCase: DbParamsCase.PascalCase)]
            public partial record GetUserCountQuery() : ICommand<int>;
            """;

        const string expectedHandler = """
            // <auto-generated/>
            #nullable enable

            using System.Threading.Tasks;
            using Dapper;
            using System.Data;

            namespace TestNamespace;

            public static class GetUserCountQueryHandler
            {
                public static async Task<int> HandleAsync(global::TestNamespace.GetUserCountQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
                {
                    await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                    var dbParams = command.ToDbParams();
                    return await connection.ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(*) FROM users", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
                }
            }
            """;

        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                ReferenceAssemblies = GetReferenceAssemblies()
            }
        }.RunAsync();
    }

    [Fact]
    public async Task ReportsErrorWhenMissingICommandInterface()
    {
        const string source = """
            using Operations.Extensions.Dapper;

            namespace TestNamespace;

            [DbCommand(sp: "test.create_user")]
            public partial record CreateUserCommand(string FirstName);
            """;

        var expected = DiagnosticResult.CompilerError("DBCOMMANDGEN002")
            .WithSpan(5, 1, 5, 66)
            .WithArguments("CreateUserCommand");

        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                ExpectedDiagnostics = { expected },
                ReferenceAssemblies = GetReferenceAssemblies()
            }
        }.RunAsync();
    }

    [Fact]
    public async Task ReportsWarningForNonQueryWithNonIntegralResult()
    {
        const string source = """
            using Operations.Extensions.Dapper;
            using Operations.Extensions.Messaging;

            namespace TestNamespace;

            [DbCommand(sp: "test.get_user", nonQuery: true)]
            public partial record GetUserCommand(int Id) : ICommand<string>;
            """;

        var expected = DiagnosticResult.CompilerWarning("DBCOMMANDGEN001")
            .WithSpan(6, 1, 6, 68)
            .WithArguments("GetUserCommand", "String");

        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                ExpectedDiagnostics = { expected },
                ReferenceAssemblies = GetReferenceAssemblies()
            }
        }.RunAsync();
    }

    [Fact]
    public async Task HandlesColumnAttributeOverride()
    {
        const string source = """
            using Operations.Extensions.Dapper;
            using Operations.Extensions.Messaging;
            using System.ComponentModel.DataAnnotations.Schema;

            namespace TestNamespace;

            [DbCommand(sp: "test.create_user", nonQuery: true, paramsCase: DbParamsCase.SnakeCase)]
            public partial record CreateUserCommand(
                string FirstName, 
                [Column("surname")] string LastName) : ICommand<int>;
            """;

        const string expectedDbOps = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial record CreateUserCommand : global::Operations.Extensions.Dapper.IDbParamsProvider
            {
                public global::System.Object ToDbParams()
                {
                    var p = new {
                        first_name = this.FirstName,
                        surname = this.LastName
                    };
                    return p;
                }
            }
            """;

        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace_CreateUserCommand.DbOps.g.cs", expectedDbOps)
                },
                ReferenceAssemblies = GetReferenceAssemblies()
            }
        }.RunAsync();
    }

    [Fact]
    public async Task HandlesPascalCaseParameters()
    {
        const string source = """
            using Operations.Extensions.Dapper;
            using Operations.Extensions.Messaging;

            namespace TestNamespace;

            [DbCommand(sp: "test.create_user", nonQuery: true, paramsCase: DbParamsCase.PascalCase)]
            public partial record CreateUserCommand(string FirstName, string LastName) : ICommand<int>;
            """;

        const string expectedDbOps = """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial record CreateUserCommand : global::Operations.Extensions.Dapper.IDbParamsProvider
            {
                public global::System.Object ToDbParams()
                {
                    var p = new {
                        FirstName = this.FirstName,
                        LastName = this.LastName
                    };
                    return p;
                }
            }
            """;

        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace_CreateUserCommand.DbOps.g.cs", expectedDbOps)
                },
                ReferenceAssemblies = GetReferenceAssemblies()
            }
        }.RunAsync();
    }

    private static string GetExpectedDbOpsForGetUsersQuery()
    {
        return """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace;

            public partial record GetUsersQuery : global::Operations.Extensions.Dapper.IDbParamsProvider
            {
                public global::System.Object ToDbParams()
                {
                    var p = new {
                        active = this.Active
                    };
                    return p;
                }
            }
            """;
    }

    private static ReferenceAssemblies GetReferenceAssemblies()
    {
        return ReferenceAssemblies.Net.Net80
            .AddPackages([
                new PackageIdentity("Dapper", "2.1.35"),
                new PackageIdentity("Npgsql", "8.0.3"),
                new PackageIdentity("System.ComponentModel.Annotations", "5.0.0")
            ]);
    }
}

// Test data types for integration testing
[DbCommand(sp: "billing.create_cashier", nonQuery: true, paramsCase: DbParamsCase.SnakeCase)]
public partial record InsertCashierCommand(Guid CashierId, string Name, string? Email) : ICommand<int>;

[DbCommand(sql: "SELECT * FROM cashiers WHERE name LIKE @namePattern", paramsCase: DbParamsCase.SnakeCase)]
public partial record SearchCashiersQuery(string NamePattern) : ICommand<IEnumerable<object>>;