// Copyright (c) ABCDEG. All rights reserved.

using Dapper;
using Operations.Extensions.Dapper;
using System.ComponentModel.DataAnnotations.Schema; // For [Column]
using Xunit;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using Operations.Extensions.SourceGenerators; // Correctly refers to the new DbCommandSourceGenerator class
using System.Collections.Immutable;
using System.Data;
using Operations.Extensions.Messaging; // For ICommand, ICommand<TResult>

namespace Operations.Extensions.Tests;

// Runtime tests for DbCommandAttribute's ToDbParams generation
[DbCommand(UseSnakeCase = true)] // Test ToDbParams with snake case
public partial record SimpleCommandRuntime(string Name, int Value);

[DbCommand(UseSnakeCase = false)] // Test ToDbParams with default (pascal case)
public partial record PascalCaseCommandRuntime([property: Column("custom_name")] string SomeProperty, int AnotherValue);


public class DbCommandSourceGeneratorTests // Renamed class
{
    // --- Runtime Tests for ToDbParams generation ---
    [Fact]
    public void SimpleCommand_Runtime_GeneratesCorrectSnakeCaseParams()
    {
        var command = new SimpleCommandRuntime("TestName", 42);
        var provider = (IDbParamsProvider)command; // Cast to the interface generated
        Assert.NotNull(provider);
        var parameters = provider.ToDbParams();
        Assert.NotNull(parameters);
        Assert.IsType<DynamicParameters>(parameters);
        var paramNames = parameters.ParameterNames.ToList();
        Assert.Contains("name", paramNames); // Due to UseSnakeCase = true
        Assert.Contains("value", paramNames); // Due to UseSnakeCase = true
    }

    [Fact]
    public void PascalCaseCommand_Runtime_GeneratesCorrectParamsWithColumnOverride()
    {
        var command = new PascalCaseCommandRuntime("PropValue", 123);
        var provider = (IDbParamsProvider)command;
        Assert.NotNull(provider);
        var parameters = provider.ToDbParams();
        Assert.NotNull(parameters);
        Assert.IsType<DynamicParameters>(parameters);
        var paramNames = parameters.ParameterNames.ToList();
        Assert.Contains("custom_name", paramNames);  // Due to [Column]
        Assert.Contains("AnotherValue", paramNames); // Due to UseSnakeCase = false (default or explicit)
    }

    // --- Source Generator Output Verification Tests ---

    private static readonly ReferenceAssemblies Net6ReferenceAssemblies =
        ReferenceAssemblies.Net.Net60.WithPackages(ImmutableArray.Create<PackageIdentity>(
            // Add any other essential NuGet package references needed by the *source code being compiled in tests* here.
            // For example, if your commands use types from Npgsql specifically, you might need that.
            // Dapper is added via AdditionalReferences when needed by generated code.
        ));

    [Fact]
    public async Task DbCommand_SpOnly_NoICommand_GeneratesDbOpsOnly()
    {
        var source = """
        using Operations.Extensions.Dapper;
        namespace TestNamespace;

        [DbCommand(sp: "test_sp")]
        public partial class MyCommand { public int Id { get; set; } }
        """;

        var expectedDbOps = """
        // <auto-generated/>
        #nullable enable

        namespace TestNamespace;

        public partial class MyCommand : global::Operations.Extensions.Dapper.IDbParamsProvider
        {
            public global::Dapper.DynamicParameters ToDbParams()
            {
                var p = new global::Dapper.DynamicParameters();
                p.Add("Id", this.Id);
                return p;
            }
        }

        """;

        var test = new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.MyCommand.DbOps.g.cs", expectedDbOps),
                    // Expect NO handler file
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(Dapper.DynamicParameters).Assembly }
            }
        };
        // Verify that only one file is generated
        test.TestState.GeneratedSources.RemoveAt(1); // Remove if a slot for handler was implicitly added by helper
        await test.RunAsync();
         Assert.Single(test.Result.GeneratedSources); // Ensure only DbOps was generated
    }

    [Fact]
    public async Task DbCommand_SqlOnly_ICommand_GeneratesDbOpsAndHandler_NonQuery()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        namespace TestNamespace;

        [DbCommand(sql: "UPDATE MyTable SET Value = @Value", UseSnakeCase = true)]
        public partial class UpdateCommand : ICommand
        {
            public string MyValue { get; set; } // Should become my_value
        }
        """;
        var expectedDbOps = """
        // <auto-generated/>
        #nullable enable

        namespace TestNamespace;

        public partial class UpdateCommand : global::Operations.Extensions.Dapper.IDbParamsProvider
        {
            public global::Dapper.DynamicParameters ToDbParams()
            {
                var p = new global::Dapper.DynamicParameters();
                p.Add("my_value", this.MyValue);
                return p;
            }
        }

        """;
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class UpdateCommandHandler
        {
            public static async Task HandleAsync(global::TestNamespace.UpdateCommand command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                await connection.ExecuteAsync(new CommandDefinition("UPDATE MyTable SET Value = @Value", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
            }
        }

        """;
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.UpdateCommand.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.UpdateCommand.UpdateCommandHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_SpOnly_ICommandInt_ReturnsAffectedTrue_GeneratesDbOpsAndHandler_ExecuteAsync()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        namespace TestNamespace;

        [DbCommand(sp: "archive_data", ReturnsAffectedRecords = true)] // ReturnsAffectedRecords = true is default
        public partial class ArchiveCommand : ICommand<int>
        {
            public DateTime OlderThan { get; set; }
        }
        """;
        var expectedDbOps = """
        // <auto-generated/>
        #nullable enable

        namespace TestNamespace;

        public partial class ArchiveCommand : global::Operations.Extensions.Dapper.IDbParamsProvider
        {
            public global::Dapper.DynamicParameters ToDbParams()
            {
                var p = new global::Dapper.DynamicParameters();
                p.Add("OlderThan", this.OlderThan);
                return p;
            }
        }

        """;
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class ArchiveCommandHandler
        {
            public static async Task<int> HandleAsync(global::TestNamespace.ArchiveCommand command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                return await connection.ExecuteAsync(new CommandDefinition("archive_data", dbParams, commandType: CommandType.StoredProcedure, cancellationToken: cancellationToken));
            }
        }

        """;
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.ArchiveCommand.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.ArchiveCommand.ArchiveCommandHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_SqlOnly_ICommandInt_ReturnsAffectedFalse_GeneratesDbOpsAndHandler_ExecuteScalarAsync()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        namespace TestNamespace;

        [DbCommand(sql: "SELECT COUNT(*) FROM Users", ReturnsAffectedRecords = false)]
        public partial class CountUsersQuery : ICommand<int> { }
        """;
        var expectedDbOps = """
        // <auto-generated/>
        #nullable enable

        namespace TestNamespace;

        public partial class CountUsersQuery : global::Operations.Extensions.Dapper.IDbParamsProvider
        {
            public global::Dapper.DynamicParameters ToDbParams()
            {
                var p = new global::Dapper.DynamicParameters();
                return p;
            }
        }

        """;
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class CountUsersQueryHandler
        {
            public static async Task<int> HandleAsync(global::TestNamespace.CountUsersQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                return await connection.ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(*) FROM Users", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
            }
        }

        """;
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.CountUsersQuery.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.CountUsersQuery.CountUsersQueryHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_Sql_ICommandIEnumerableT_GeneratesQueryAsyncHandler()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        using System.Collections.Generic;
        namespace TestNamespace;

        public class UserPoco { public int Id { get; set; } public string Name { get; set; } }

        [DbCommand(sql: "SELECT Id, Name FROM Users WHERE Age > @AgeLimit", UseSnakeCase = true)]
        public partial class GetUsersQuery : ICommand<IEnumerable<UserPoco>>
        {
            public int AgeLimit { get; set; } // -> age_limit
        }
        """;
        var expectedDbOps = """
        // <auto-generated/>
        #nullable enable

        namespace TestNamespace;

        public partial class GetUsersQuery : global::Operations.Extensions.Dapper.IDbParamsProvider
        {
            public global::Dapper.DynamicParameters ToDbParams()
            {
                var p = new global::Dapper.DynamicParameters();
                p.Add("age_limit", this.AgeLimit);
                return p;
            }
        }

        """;
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class GetUsersQueryHandler
        {
            public static async Task<global::System.Collections.Generic.IEnumerable<global::TestNamespace.UserPoco>> HandleAsync(global::TestNamespace.GetUsersQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                return await connection.QueryAsync<global::TestNamespace.UserPoco>(new CommandDefinition("SELECT Id, Name FROM Users WHERE Age > @AgeLimit", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
            }
        }

        """;
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.GetUsersQuery.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.GetUsersQuery.GetUsersQueryHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_Sql_ICommandT_GeneratesQueryFirstOrDefaultAsyncHandler()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        namespace TestNamespace;

        public class ItemPoco { public Guid ItemId { get; set; } public string Description { get; set; } }

        [DbCommand(sql: "SELECT ItemId, Description FROM Items WHERE ItemId = @ItemId", UseSnakeCase = false)]
        public partial class GetItemQuery : ICommand<ItemPoco>
        {
            public Guid ItemId { get; set; } // Parameter name will be ItemId
        }
        """;
        var expectedDbOps = """
        // <auto-generated/>
        #nullable enable

        namespace TestNamespace;

        public partial class GetItemQuery : global::Operations.Extensions.Dapper.IDbParamsProvider
        {
            public global::Dapper.DynamicParameters ToDbParams()
            {
                var p = new global::Dapper.DynamicParameters();
                p.Add("ItemId", this.ItemId);
                return p;
            }
        }

        """;
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class GetItemQueryHandler
        {
            public static async Task<global::TestNamespace.ItemPoco> HandleAsync(global::TestNamespace.GetItemQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                return await connection.QueryFirstOrDefaultAsync<global::TestNamespace.ItemPoco>(new CommandDefinition("SELECT ItemId, Description FROM Items WHERE ItemId = @ItemId", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
            }
        }

        """;
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.GetItemQuery.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.GetItemQuery.GetItemQueryHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_NoSpNoSql_UseSnakeCaseTrue_GeneratesDbOpsOnly_SnakeCaseParams()
    {
        var source = """
        using Operations.Extensions.Dapper;
        namespace TestNamespace;

        [DbCommand(UseSnakeCase = true)] // No sp/sql, only ToDbParams configuration
        public partial class ConfigOnlyCommand
        {
            public string SomeProperty { get; set; } // -> some_property
            public int AnotherID { get; set; }    // -> another_id
        }
        """;
        var expectedDbOps = """
        // <auto-generated/>
        #nullable enable

        namespace TestNamespace;

        public partial class ConfigOnlyCommand : global::Operations.Extensions.Dapper.IDbParamsProvider
        {
            public global::Dapper.DynamicParameters ToDbParams()
            {
                var p = new global::Dapper.DynamicParameters();
                p.Add("some_property", this.SomeProperty);
                p.Add("another_id", this.AnotherID);
                return p;
            }
        }

        """;
        var test = new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.ConfigOnlyCommand.DbOps.g.cs", expectedDbOps),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(Dapper.DynamicParameters).Assembly }
            }
        };
        // Explicitly verify no other files generated
        test.TestState.GeneratedSources.RemoveAt(1); // Remove if a slot for handler was implicitly added by helper
        await test.RunAsync();
        Assert.Single(test.Result.GeneratedSources);
    }
}
