// Copyright (c) ABCDEG. All rights reserved.

using Dapper;
using Operations.Extensions.Dapper;
using System.ComponentModel.DataAnnotations.Schema; // For [Column]
using Xunit;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using Operations.Extensions.SourceGenerators;
using System.Collections.Immutable;
using System.Data;
using Operations.Extensions.Messaging;
using System.Collections.Generic; // For IEnumerable in helper
using System.Text; // For StringBuilder in helper

// Required for NpgsqlDataSource in generated code
using Npgsql;


namespace Operations.Extensions.Tests;

// Runtime tests for DbCommandAttribute's ToDbParams generation
[DbCommand(UseSnakeCase = true)]
public partial record SimpleCommandRuntime(string Name, int Value);

[DbCommand(UseSnakeCase = false)]
public partial record PascalCaseCommandRuntime([property: Column("custom_name")] string SomeProperty, int AnotherValue);


public class DbCommandSourceGeneratorTests
{
    // --- Helper Constants and Methods ---
    public const string ICommandInterfacesConstant = @"
    namespace Operations.Extensions.Messaging
    {
        public interface ICommand { }
        public interface ICommand<TResult> : ICommand { }
    }
    ";

    private string GetExpectedToDbParamsSource(string className, IEnumerable<(string PropName, string ParamName)> properties, string ns = "TestNamespace", bool isRecord = true, string? typeKindOverride = null)
    {
        var propsBuilder = new StringBuilder();
        foreach (var (propName, paramName) in properties)
        {
            propsBuilder.AppendLine($"            p.Add(\"{paramName}\", this.{propName});");
        }
        string kind = typeKindOverride ?? (isRecord ? "partial record" : "partial class");
        // Ensure there's a space if kind is not empty and doesn't end with one (e.g. "partial record class")
        if (!string.IsNullOrEmpty(kind) && !kind.EndsWith(" ")) kind += " ";


        return @$"// <auto-generated/>
#nullable enable

namespace {ns};

public {kind}{className} : global::Operations.Extensions.Dapper.IDbParamsProvider
{{
    public global::Dapper.DynamicParameters ToDbParams()
    {{
        var p = new global::Dapper.DynamicParameters();
{propsBuilder}            return p;
    }}
}}
";
    }


    // --- Runtime Tests for ToDbParams generation ---
    [Fact]
    public void SimpleCommand_Runtime_GeneratesCorrectSnakeCaseParams()
    {
        var command = new SimpleCommandRuntime("TestName", 42);
        var provider = (IDbParamsProvider)command;
        Assert.NotNull(provider);
        var parameters = provider.ToDbParams();
        Assert.NotNull(parameters);
        Assert.IsType<DynamicParameters>(parameters);
        var paramNames = parameters.ParameterNames.ToList();
        Assert.Contains("name", paramNames);
        Assert.Contains("value", paramNames);
    }

    [Fact]
    public void PascalCaseCommand_Runtime_GeneratesCorrectParamsWithColumnOverride()
    {
        var command = new PascalCaseCommandRuntime("PropValue", 123);
        var provider = (IDbParamsProvider)command;
        Assert.NotNull(provider);
        var parameters = provider.ToDbParams();
        Assert.NotNull(parameters);
        Assert.IsType<DynamicParameters>(parameters);
        var paramNames = parameters.ParameterNames.ToList();
        Assert.Contains("custom_name", paramNames);
        Assert.Contains("AnotherValue", paramNames);
    }

    // --- Source Generator Output Verification Tests ---

    private static readonly ReferenceAssemblies Net6ReferenceAssemblies =
        ReferenceAssemblies.Net.Net60.WithPackages(ImmutableArray.Create<PackageIdentity>(
            // Npgsql needed for NpgsqlDataSource in generated handlers
            new PackageIdentity("Npgsql", "7.0.0")
        ));

    [Fact]
    public async Task DbCommand_SpOnly_NoICommand_GeneratesDbOpsOnly()
    {
        var source = """
        using Operations.Extensions.Dapper;
        namespace TestNamespace;

        [DbCommand(sp: "test_sp")] // nonQuery defaults to false
        public partial class MyCommand { public int Id { get; set; } }
        """;

        var expectedDbOps = GetExpectedToDbParamsSource("MyCommand", new[] { ("Id", "Id") }, isRecord:false, typeKindOverride: "partial class");

        var test = new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source, ICommandInterfacesConstant }, // Added ICommandInterfaces for completeness if other tests need it implicitly
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.MyCommand.DbOps.g.cs", expectedDbOps),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(Dapper.DynamicParameters).Assembly, typeof(NpgsqlDataSource).Assembly }
            }
        };
        test.TestState.GeneratedSources.RemoveAt(1);
        await test.RunAsync();
        Assert.Single(test.Result.GeneratedSources);
    }

    [Fact]
    public async Task DbCommand_SqlOnly_ICommand_GeneratesDbOpsAndHandler_NonQueryImplicit()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        namespace TestNamespace;

        // nonQuery defaults to false, but for ICommand (non-generic), it's treated as non-query by generator.
        [DbCommand(sql: "UPDATE MyTable SET Value = @Value", UseSnakeCase = true)]
        public partial class UpdateCommand : ICommand
        {
            public string MyValue { get; set; }
        }
        """;
        var expectedDbOps = GetExpectedToDbParamsSource("UpdateCommand", new[] { ("MyValue", "my_value") }, isRecord: false, typeKindOverride: "partial class");
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class UpdateCommandHandler
        {
            public static async Task HandleAsync(global::TestNamespace.UpdateCommand command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                await connection.ExecuteAsync(new CommandDefinition("UPDATE MyTable SET Value = @Value", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
            }
        }

        """;
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source, ICommandInterfacesConstant },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.UpdateCommand.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.UpdateCommand.UpdateCommandHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly, typeof(NpgsqlDataSource).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_SpOnly_ICommandInt_ReturnsAffectedTrue_GeneratesDbOpsAndHandler_ExecuteAsync()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        using System; // For DateTime (if it was used)

        namespace TestNamespace;

        // nonQuery defaults to false. ReturnsAffectedRecords = true is default.
        [DbCommand(sp: "archive_data" /* ReturnsAffectedRecords = true is default */)]
        public partial class ArchiveCommand : ICommand<int>
        {
            public DateTime OlderThan { get; set; }
        }
        """;
        var expectedDbOps = GetExpectedToDbParamsSource("ArchiveCommand", new[] { ("OlderThan", "OlderThan") }, isRecord: false, typeKindOverride: "partial class");
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class ArchiveCommandHandler
        {
            public static async Task<int> HandleAsync(global::TestNamespace.ArchiveCommand command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                return await connection.ExecuteAsync(new CommandDefinition("archive_data", dbParams, commandType: CommandType.StoredProcedure, cancellationToken: cancellationToken));
            }
        }

        """;
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source, ICommandInterfacesConstant },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.ArchiveCommand.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.ArchiveCommand.ArchiveCommandHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly, typeof(NpgsqlDataSource).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_SqlOnly_ICommandInt_ReturnsAffectedFalse_GeneratesDbOpsAndHandler_ExecuteScalarAsync()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        namespace TestNamespace;

        // nonQuery defaults to false.
        [DbCommand(sql: "SELECT COUNT(*) FROM Users", ReturnsAffectedRecords = false)]
        public partial class CountUsersQuery : ICommand<int> { }
        """;
        var expectedDbOps = GetExpectedToDbParamsSource("CountUsersQuery", Array.Empty<(string,string)>(), isRecord: false, typeKindOverride: "partial class");
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class CountUsersQueryHandler
        {
            public static async Task<int> HandleAsync(global::TestNamespace.CountUsersQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                return await connection.ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(*) FROM Users", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
            }
        }

        """;
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source, ICommandInterfacesConstant },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.CountUsersQuery.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.CountUsersQuery.CountUsersQueryHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly, typeof(NpgsqlDataSource).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_Sql_ICommandIEnumerableT_GeneratesQueryAsyncHandler()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        using System.Collections.Generic;
        namespace TestNamespace;

        public class UserPoco { public int Id { get; set; } public string Name { get; set; } }

        // nonQuery defaults to false
        [DbCommand(sql: "SELECT Id, Name FROM Users WHERE Age > @AgeLimit", UseSnakeCase = true)]
        public partial class GetUsersQuery : ICommand<IEnumerable<UserPoco>>
        {
            public int AgeLimit { get; set; }
        }
        """;
        var expectedDbOps = GetExpectedToDbParamsSource("GetUsersQuery", new[] { ("AgeLimit", "age_limit") }, isRecord: false, typeKindOverride: "partial class");
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class GetUsersQueryHandler
        {
            public static async Task<global::System.Collections.Generic.IEnumerable<global::TestNamespace.UserPoco>> HandleAsync(global::TestNamespace.GetUsersQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                return await connection.QueryAsync<global::TestNamespace.UserPoco>(new CommandDefinition("SELECT Id, Name FROM Users WHERE Age > @AgeLimit", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
            }
        }

        """;
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source, ICommandInterfacesConstant },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.GetUsersQuery.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.GetUsersQuery.GetUsersQueryHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly, typeof(NpgsqlDataSource).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_Sql_ICommandT_GeneratesQueryFirstOrDefaultAsyncHandler()
    {
        var source = """
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        using System; // For Guid
        namespace TestNamespace;

        public class ItemPoco { public Guid ItemId { get; set; } public string Description { get; set; } }

        // nonQuery defaults to false
        [DbCommand(sql: "SELECT ItemId, Description FROM Items WHERE ItemId = @ItemId", UseSnakeCase = false)]
        public partial class GetItemQuery : ICommand<ItemPoco>
        {
            public Guid ItemId { get; set; }
        }
        """;
        var expectedDbOps = GetExpectedToDbParamsSource("GetItemQuery", new[] { ("ItemId", "ItemId") }, isRecord: false, typeKindOverride: "partial class");
        var expectedHandler = """
        // <auto-generated/>
        #nullable enable

        using System.Threading.Tasks;
        using Dapper;
        using System.Data;

        namespace TestNamespace;

        public static class GetItemQueryHandler
        {
            public static async Task<global::TestNamespace.ItemPoco?> HandleAsync(global::TestNamespace.GetItemQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
            {
                await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
                var dbParams = command.ToDbParams();
                return await connection.QueryFirstOrDefaultAsync<global::TestNamespace.ItemPoco>(new CommandDefinition("SELECT ItemId, Description FROM Items WHERE ItemId = @ItemId", dbParams, commandType: CommandType.Text, cancellationToken: cancellationToken));
            }
        }

        """;
        // Note: Added ? to Task<global::TestNamespace.ItemPoco?> for QueryFirstOrDefaultAsync
        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source, ICommandInterfacesConstant },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.GetItemQuery.DbOps.g.cs", expectedDbOps),
                    (typeof(DbCommandSourceGenerator), "TestNamespace.GetItemQuery.GetItemQueryHandler.g.cs", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(ICommand).Assembly, typeof(Dapper.DynamicParameters).Assembly, typeof(NpgsqlDataSource).Assembly }
            }
        }.RunAsync();
    }

    [Fact]
    public async Task DbCommand_NoSpNoSql_UseSnakeCaseTrue_GeneratesDbOpsOnly_SnakeCaseParams()
    {
        var source = """
        using Operations.Extensions.Dapper;
        namespace TestNamespace;

        [DbCommand(UseSnakeCase = true)]
        public partial class ConfigOnlyCommand
        {
            public string SomeProperty { get; set; }
            public int AnotherID { get; set; }
        }
        """;
        var expectedDbOps = GetExpectedToDbParamsSource("ConfigOnlyCommand", new[] { ("SomeProperty", "some_property"), ("AnotherID", "another_id") }, isRecord: false, typeKindOverride: "partial class");
        var test = new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources = { source, ICommandInterfacesConstant },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), "TestNamespace.ConfigOnlyCommand.DbOps.g.cs", expectedDbOps),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(Dapper.DynamicParameters).Assembly, typeof(NpgsqlDataSource).Assembly }
            }
        };
        test.TestState.GeneratedSources.RemoveAt(1);
        await test.RunAsync();
        Assert.Single(test.Result.GeneratedSources);
    }

    // --- New tests for NonQuery property ---

    [Fact]
    public async Task CommandWithIntResult_NonQueryTrue_GeneratesExecuteAsync()
    {
        var source = @"
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        using System;

        namespace TestNamespace;

        // NonQuery = true should override returnsAffectedRecords behavior for ICommand<int>
        [DbCommand(sp: ""sp_update_data"", returnsAffectedRecords: false, nonQuery: true)]
        public partial record MyIntCommandNonQuery : ICommand<int>
        {
            public Guid Id { get; set; }
        }
        ";

        var expectedHandler = @"// <auto-generated/>
#nullable enable

using System.Threading.Tasks;
using Dapper;
using System.Data;

namespace TestNamespace;

public static class MyIntCommandNonQueryHandler
{
    public static async Task<int> HandleAsync(global::TestNamespace.MyIntCommandNonQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
    {
        await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
        var dbParams = command.ToDbParams();
        return await connection.ExecuteAsync(new CommandDefinition(""sp_update_data"", dbParams, commandType: CommandType.StoredProcedure, cancellationToken: cancellationToken));
    }
}
";

        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>()
        {
            TestState =
            {
                Sources = { source, ICommandInterfacesConstant },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), ""TestNamespace.MyIntCommandNonQuery.DbOps.g.cs"", GetExpectedToDbParamsSource(""MyIntCommandNonQuery"", new[] { (""Id"", ""Id"") }, ""TestNamespace"", true)),
                    (typeof(DbCommandSourceGenerator), ""TestNamespace.MyIntCommandNonQuery.MyIntCommandNonQueryHandler.g.cs"", expectedHandler),
                },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = {
                    typeof(DbCommandAttribute).Assembly,
                    typeof(Dapper.SqlMapper).Assembly,
                    typeof(Npgsql.NpgsqlDataSource).Assembly,
                    typeof(ICommand).Assembly
                }
            },
        }.RunAsync();
    }

    [Fact]
    public async Task CommandWithModelResult_NonQueryTrue_GeneratesWarningAndExecuteAsync()
    {
        var someModelSource = @"namespace TestNamespace { public class SomeModel { public string? Data { get; set; } } }";
        var source = @"
        using Operations.Extensions.Dapper;
        using Operations.Extensions.Messaging;
        using System;

        namespace TestNamespace;

        [DbCommand(sp: ""sp_log_action"", nonQuery: true)]
        public partial record MyModelCommandNonQuery : ICommand<SomeModel>
        {
            public Guid Id { get; set; }
        }
        ";

        var expectedHandler = @"// <auto-generated/>
#nullable enable

using System.Threading.Tasks;
using Dapper;
using System.Data;

namespace TestNamespace;

public static class MyModelCommandNonQueryHandler
{
    public static async Task<global::TestNamespace.SomeModel?> HandleAsync(global::TestNamespace.MyModelCommandNonQuery command, global::Npgsql.NpgsqlDataSource dataSource, global::System.Threading.CancellationToken cancellationToken = default)
    {
        await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
        var dbParams = command.ToDbParams();
        await connection.ExecuteAsync(new CommandDefinition(""sp_log_action"", dbParams, commandType: CommandType.StoredProcedure, cancellationToken: cancellationToken));
        return default(global::TestNamespace.SomeModel);
    }
}
";

        var expectedDiagnostic = CSharpSourceGeneratorVerifier<DbCommandSourceGenerator>.Diagnostic(""DBCOMMANDGEN001"")
            .WithMessageFormat(""DbCommandAttribute's NonQuery property is true for command '{0}' which implements ICommand<{1}>. This is unusual as NonQuery typically implies no data is returned. The generated handler will execute the command and attempt to return default({1})."")
            .WithArguments(""MyModelCommandNonQuery"", ""global::TestNamespace.SomeModel"")
            .WithSeverity(DiagnosticSeverity.Warning)
            .WithLocation(0); // Default location if not specified more precisely

        await new CSharpSourceGeneratorTest<DbCommandSourceGenerator, XUnitVerifier>()
        {
            TestState =
            {
                Sources = { source, someModelSource, ICommandInterfacesConstant },
                GeneratedSources =
                {
                    (typeof(DbCommandSourceGenerator), ""TestNamespace.MyModelCommandNonQuery.DbOps.g.cs"", GetExpectedToDbParamsSource(""MyModelCommandNonQuery"", new[] { (""Id"", ""Id"") }, ""TestNamespace"", true)),
                    (typeof(DbCommandSourceGenerator), ""TestNamespace.MyModelCommandNonQuery.MyModelCommandNonQueryHandler.g.cs"", expectedHandler),
                },
                ExpectedDiagnostics = { expectedDiagnostic },
                ReferenceAssemblies = Net6ReferenceAssemblies,
                AdditionalReferences = { typeof(DbCommandAttribute).Assembly, typeof(Dapper.SqlMapper).Assembly, typeof(Npgsql.NpgsqlDataSource).Assembly, typeof(ICommand).Assembly }
            },
        }.RunAsync();
    }
}
