// <auto-generated/>
#nullable enable

using Operations.Extensions.Dapper;

namespace Billing.Cashier.Commands;

// <generated_implementation>
partial record CreateCashierCommand : IDbParamsProvider
{
    public object ToDbParams()
    {
        var p = new
        {
            cashier_id = this.CashierId,
            name = this.Name,
            email = this.Email
        };
        return p;
    }
}
// </generated_implementation>