// <auto-generated/>
#nullable enable

using Dapper;
using System.Data.Common;

namespace Billing.Users.Commands;

// <generated_handler>
public static class CreateUserCommandHandler
{
    public static async Task<int> HandleAsync(
        CreateUserCommand command,
        DbDataSource datasource,
        CancellationToken cancellationToken = default)
    {
        await using var connection = await datasource.OpenConnectionAsync(cancellationToken);
        var dbParams = command.ToDbParams();
        return await SqlMapper.ExecuteAsync(
            connection,
            new CommandDefinition(
                "users.create_user",
                dbParams,
                commandType: System.Data.CommandType.StoredProcedure,
                cancellationToken: cancellationToken));
    }
}
// </generated_handler>