// <auto-generated/>
#nullable enable

using Dapper;
using Microsoft.Extensions.DependencyInjection;
using System.Data.Common;

namespace Billing.Examples;

// <keyed_handler>
public static class LogUserActionCommandHandler
{
    public static async Task<int> HandleAsync(
        LogUserActionCommand command,
        [FromKeyedServices("AuditWriter")] DbDataSource datasource,
        CancellationToken cancellationToken = default)
    {
        await using var connection = await datasource.OpenConnectionAsync(cancellationToken);
        var dbParams = command.ToDbParams();
        return await SqlMapper.ExecuteAsync(
            connection,
            new CommandDefinition(
                "audit.log_user_action",
                dbParams,
                commandType: System.Data.CommandType.StoredProcedure,
                cancellationToken: cancellationToken));
    }
}
// </keyed_handler>