// Copyright (c) ABCDEG. All rights reserved.

namespace Operations.Extensions.Abstractions.Dapper;

/// <summary>
///     Specifies the database column name for a parameter in a database command.
/// </summary>
/// <remarks>
///     Use this attribute on method parameters to map them to specific database column names
///     when the parameter name doesn't match the column name. This is particularly useful
///     when working with database commands generated by source generators.
/// </remarks>
/// <example>
///     <code>
/// public Task&lt;User&gt; GetUserAsync([Column("user_id")] int id, [Column("is_active")] bool active);
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Parameter)]
public sealed class ColumnAttribute(string name) : Attribute
{
    /// <summary>
    ///     Gets the database column name.
    /// </summary>
    /// <value>
    ///     The name of the database column that this parameter maps to.
    /// </value>
    public string Name { get; } = name;
}
