@Billing_Api = http://localhost:5079

### Create Cashier
POST {{Billing_Api}}/Cashiers/
Accept: application/json
Content-Type: application/json

{
    "name": "John Doe"
}

### Get Cashiers
GET {{Billing_Api}}/Cashiers/
Accept: application/json


### Get Cashiers
GET {{Billing_Api}}/Cashiers/fake-error
Accept: application/json
